# Generated by Django 3.0.6 on 2020-06-14 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0002_auto_20200614_0957'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdatabase',
            name='profile_title',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
