# Generated by Django 3.0.6 on 2020-06-14 14:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0003_userdatabase_profile_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='connections',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(blank=True, default='sent', max_length=30, null=True)),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('receiver', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='receiver', to='connect.UserDataBase')),
                ('sender', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender', to='connect.UserDataBase')),
            ],
        ),
    ]
