# Generated by Django 3.0.6 on 2020-06-20 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0004_connections'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connections',
            name='status',
            field=models.CharField(blank=True, default='Sent', max_length=30, null=True),
        ),
    ]
