# Generated by Django 3.0.6 on 2020-06-22 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connect', '0005_auto_20200620_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connections',
            name='status',
            field=models.CharField(blank=True, default='sent', max_length=30, null=True),
        ),
    ]
